name: testing
on: [pull_request, push]

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - run: pip install pipenv
      - run: pipenv --version
      - run: pipenv install --dev
      - name: run test
        run: pipenv run test
      - name: result
        if: ${{ success() }}
        run: echo "success"