name: run_test
on: [pull_request, push]

env:
  PYTHON_VERSION: 3.8

jobs:
  show_pipenv_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run:
          pip install pipenv
      - name: Install dev packages
        run:
          pipenv install --dev
      - name: Run test
        run: 
          pipenv run test
