name: testing
on: [pull_request, push]

jobs:
  show_pipenv_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump env context 
        run: echo '${{ toJSON(env) }}' 
      - run: git checkout main
      - run: git branch
      - run: pip install pipenv
      - run: pipenv --version
      - run: pipenv install --dev
      - name: run test
        run: pipenv run test
      - name: result
        if: ${{ success() }}
        run: echo "success"