name: testing
on: [pull_request, push]

jobs:
  show_pipenv_version:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ job.status }}
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: work
        #   fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - run: |
          git branch
          git log
          # git checkout b3
      - run: |
          echo ${{ github.workspace }}
          pwd
          ls
      - run: |
          pip install pipenv
          pipenv --version
      - run: |
          pipenv install --dev
      - name: run test
        run: pipenv run test
      - run: echo ${{ job.status }}
      - name: result
        if: ${{ success() }}
        run: echo "success"