name: testing
on: [pull_request, push]

jobs:
  show_pipenv_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: git checkout b1
      - run: git branch
      - run: pip install pipenv
      - run: pipenv --version
      - run: pipenv install --dev
      - name: run test
        run: pipenv run test
      - name: result
        if: ${{ success() }}
        run: echo "success"