name: run_test
on: [pull_request, push]

env:
  PYTHON_VERSION: 3.9
  CI: false

jobs:
  show_pipenv_version:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.CI }}
      - run: echo $CI
      - name: Dump env object 
        run: echo '${{ toJSON(env) }}' 
      - run: env
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run:
          pip install pipenv
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dev packages
        run:
          pipenv install --dev
      - name: Run test
        run: 
          pipenv run test
