name: Action Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: macos-11
    steps:
      - name: python version
        run: python --version
      - name: echo CONDA
        run: echo $CONDA
      - run: pwd
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo ${{ github.workspace }}
      - run: ls
      - run: echo ${{ github.repository }}
